theme: minima
minima:
  skin: dark
title: rickylog
author: Ricky Zacharias
email: ricky@definitely.website
description: > # this means to ignore newlines until "baseurl:"
  Philadelphia public defender just sort of thinking out-loud?
#header_pages:
#  - index.md
#  - Dick.md

# social links
twitter_username: rickyz # DO NOT include the @ character, or else the build will fail!
github_username:  ongepotchket # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
